FROM node:18

RUN mkdir -p /usr/src/app/node_modules

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=dev
RUN npm install dotenv-vault -g

COPY .env.vault ./

RUN npx dotenv-vault pull development

COPY src ./src

CMD ["npm", "run", "dev"]