version: '3'
services:
  bot-js:
    container_name: nodejs-bot
    build: 
      context: .
      dockerfile: Dockerfile.${DOCKERFILE_ENV:-dev}
    volumes:
      - ./src:/usr/src/app/src/
      - ./logs:/usr/src/app/logs/
    environment:
      # Used by config.ts to load the keys when running in docker
      - DOCKER_SECRETS_ENV_KEYS_PATH=/run/secrets/env_keys
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    env_file:
      - .env
    secrets:
      - env_keys

secrets:
  env_keys:
    file: ./.env.keys