# Build the project
FROM node:18

RUN mkdir -p /usr/src/app/node_modules

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -D

# Get .env file
COPY .env ./
COPY .env.quesito ./

# Copy the project and compile it
COPY tsconfig.json ./
COPY src ./src

# Run the project
CMD ["npm", "run", "dev"]