# Build the project
FROM node:18

RUN mkdir -p /usr/src/app/node_modules

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -D

# Get .env file
RUN npm install dotenv-vault -g

COPY .env.vault ./

RUN npx dotenv-vault pull development

# Copy the project and compile it
COPY tsconfig.json ./
COPY src ./src

# Run the project
CMD ["npm", "run", "dev"]